prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/hotel_details.sql
@@application/shared_components/navigation/lists/comments.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/hakimi_untitled_1_png.sql
@@application/shared_components/files/untitled_1_png.sql
@@application/shared_components/files/untitled_3_png.sql
@@application/shared_components/files/filed_str_star_svgrepo_com_svg.sql
@@application/shared_components/files/icons_logo_with_back_png.sql
@@application/shared_components/files/icons_logo_without_back_png.sql
@@application/shared_components/files/hakimi_herologin_png.sql
@@application/shared_components/files/hakimi_maroc_can_2025_jpeg.sql
@@application/shared_components/files/zalij.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/security/app_access_control/adminprincipale.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_items/user_role.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_due.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_initiated.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_priority.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_state.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_type.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/region/hospital_cards.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/shared_components/security/authentications/custom_users_table_login.sql
@@application/shared_components/navigation/search_config/search_restaurants.sql
@@application/shared_components/navigation/search_config/bus_searche.sql
@@application/shared_components/navigation/search_config/search_pharmasy.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00015.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00040.sql
@@application/pages/page_00042.sql
@@application/pages/page_00043.sql
@@application/pages/page_09999.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
